INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('молоко', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('корица', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('имбирь', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('яйца', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('крахмал кукурузный', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('сахар', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('масло сливочное', 9);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('тыква', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('желатин', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('мука', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('вода', 10);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('какао', 10);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('соль', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('белая рыба', 1);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('лимон', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('белое вино', 11);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('сливки', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('булочки', 12);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('лук', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('чеснок', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('коричневый сахар', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('паприка', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('томатная паста', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('бекон', 5);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('куриный фарш', 6);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('сыр', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('листья салата', 13);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('оливковое масло ', 9);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('цукини', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('чили', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('горчица', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('базилик', 13);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('лайм', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('томаты', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('моцарелла', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('авокадо', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('ананас', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('баклажаны', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('перец сладкий', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('растительное масло', 9);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('томаты в соку', 14);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('тимьян', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('свинина', 5);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('томатный соус', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('мед', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('тростниковый сахар', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('уксус', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('пиво', 11);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('кукуруза', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('курица', 6);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('фета', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('бульон', 6);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('разрыхлитель', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('сода', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('тыквенное пюре', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('сахарная пудра', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('миндальная мука', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('творожный сыр', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('цитрусовый сок', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('ягоды', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('свекла', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('стейк', 5);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('лук шалот', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('мясо', 5);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('соевый соус', 8);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('шалфей', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('морковь', 3);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('орегано сухой', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('лепешка', 12);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('груша', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('яблоко', 2);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('мята', 4);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('сухари для панировки', 12);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('пармезан', 7);
INSERT INTO chief.ingredients (name, category_of_ingredient) VALUES ('дрожжи', 8);