INSERT INTO chief.ingredient_categories (name) VALUES ('Рыба');
INSERT INTO chief.ingredient_categories (name) VALUES ('Фрукты');
INSERT INTO chief.ingredient_categories (name) VALUES ('Овощи');
INSERT INTO chief.ingredient_categories (name) VALUES ('Специи и травы');
INSERT INTO chief.ingredient_categories (name) VALUES ('Мясо');
INSERT INTO chief.ingredient_categories (name) VALUES ('Домашняя птица');
INSERT INTO chief.ingredient_categories (name) VALUES ('Молочные и яйцепродукты');
INSERT INTO chief.ingredient_categories (name) VALUES ('Вкусовые товары');
INSERT INTO chief.ingredient_categories (name) VALUES ('Жиры и масла');
INSERT INTO chief.ingredient_categories (name) VALUES ('Продукты для питья');
INSERT INTO chief.ingredient_categories (name) VALUES ('Алкогольные напитки');
INSERT INTO chief.ingredient_categories (name) VALUES ('Хлебобулочные изделия');
INSERT INTO chief.ingredient_categories (name) VALUES ('Зелень');
INSERT INTO chief.ingredient_categories (name) VALUES ('Консервация');